// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, express, handlePromise, installCheck, setupErrorHandler, setupMiddlewares, setupRouters, setupSession;

  express = require('express');

  Promise = require('bluebird');

  handlePromise = function(handler) {
    return function(req, res) {
      return Promise.resolve().then(function() {
        return handler(req, res);
      }).then(function(result) {
        return res.sendResult(result || {});
      })["catch"](function(error) {
        return res.sendError(error);
      });
    };
  };

  express.Router.getPromise = function(path, callback) {
    return this.get.call(this, path, handlePromise(callback));
  };

  express.Router.postPromise = function(path, callback) {
    return this.post.call(this, path, handlePromise(callback));
  };

  express.Router.putPromise = function(path, callback) {
    return this.put.call(this, path, handlePromise(callback));
  };

  express.Router.deletePromise = function(path, callback) {
    return this["delete"].call(this, path, handlePromise(callback));
  };

  setupMiddlewares = function(app, config) {
    var bodyParser;
    bodyParser = require('body-parser');
    app.use(require('compression')());
    app.use(bodyParser.json({
      limit: '10mb'
    }));
    app.use(bodyParser.urlencoded({
      limit: '10mb',
      extended: true
    }));
    app.use(require('cookie-parser')());
  };

  setupSession = function(app, config) {
    var RedisStore, redis, redis_client, session, sessionStore;
    session = require('express-session');
    redis = require('redis');
    RedisStore = require('connect-redis')(session);
    redis_client = redis.createClient(config.redis_port, config.redis_host || '127.0.0.1');
    sessionStore = new RedisStore({
      client: redis_client,
      ttl: config.session_ttl,
      pass: config.redis_password
    });
    sessionStore.on('disconnect', function() {
      console.log("RedisStore for express is disconnected. Exit the process...");
      setTimeout(function() {
        process.exit(0);
      }, 1000);
    });
    app.use(session({
      store: sessionStore,
      secret: config.session_secret,
      cookie: {
        maxAge: config.session_ttl * 1000
      },
      saveUninitialized: false,
      resave: true
    }));
  };

  setupRouters = function(app, config) {
    var ctor, path, router, _ref;
    _ref = config.routers;
    for (path in _ref) {
      ctor = _ref[path];
      router = express.Router();
      if (!path) {
        installCheck(router, config);
      }
      ctor(router, app);
      if (path) {
        app.use(path, router);
      } else {
        app.use(router);
      }
    }
  };

  installCheck = function(router, config) {
    var worker_num;
    worker_num = process.env.WORKER_NUM;
    return router.get('/api/check', function(req, res) {
      var data;
      req.skip_logging = true;
      data = {
        memory: process.memoryUsage(),
        uptime: process.uptime(),
        dir: config.project_root,
        worker_num: worker_num
      };
      if (req.session == null) {
        data.session = false;
        res.status(400);
      }
      res.type('application/json; charset=utf-8');
      return res.json(data);
    });
  };

  setupErrorHandler = function(app, config) {
    app.use(function(err, req, res, next) {
      var code;
      if (!(err instanceof Error)) {
        err = new Error(err);
      }
      res.error = err;
      code = err.status || res.statusCode;
      if (code < 400) {
        code = 500;
      }
      res.type('application/json; charset=utf-8').status(code).json({
        error: err.message
      });
    });
  };

  module.exports = function(config) {
    var app;
    app = express();
    app.set('trust proxy', true);
    if (config.log4js_config) {
      app.use(require('./logger')(config));
    }
    setupMiddlewares(app, config);
    setupSession(app, config);
    setupRouters(app, config);
    setupErrorHandler(app, config);
    app.response._errors = config.errors || {};
    require('./response').install(app.response);
    return app;
  };

}).call(this);
